name: Build project

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build       

      - name: Build debug APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Check files
        run: ls -al app/build/outputs/apk/release


      - name: Archive bbuild
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      
    
